name: qualia-gtk-theme
version: '1.0'
architectures:
  - build-on: amd64
    run-on: all
summary: qualia GTK theme
description: |
  A Yaru and Libadwaita inspired theme designed to provide a consistent experience on GTK desktops.
build-base: core20
base: bare
compression: lzo

grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/qualia
        - $SNAP/share/themes/qualia-bark
        - $SNAP/share/themes/qualia-lightblue
        - $SNAP/share/themes/qualia-blue
        - $SNAP/share/themes/qualia-magenta
        - $SNAP/share/themes/qualia-olive
        - $SNAP/share/themes/qualia-prussiangreen
        - $SNAP/share/themes/qualia-purple
        - $SNAP/share/themes/qualia-pink
        - $SNAP/share/themes/qualia-red
        - $SNAP/share/themes/qualia-sage
        - $SNAP/share/themes/qualia-viridian
        - $SNAP/share/themes/qualia-dark
        - $SNAP/share/themes/qualia-bark-dark
        - $SNAP/share/themes/qualia-lightblue-dark
        - $SNAP/share/themes/qualia-blue-dark
        - $SNAP/share/themes/qualia-magenta-dark
        - $SNAP/share/themes/qualia-olive-dark
        - $SNAP/share/themes/qualia-prussiangreen-dark
        - $SNAP/share/themes/qualia-purple-dark
        - $SNAP/share/themes/qualia-pink-dark
        - $SNAP/share/themes/qualia-red-dark
        - $SNAP/share/themes/qualia-sage-dark
        - $SNAP/share/themes/qualia-viridian-dark
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/qualia
        - $SNAP/share/icons/qualia-bark
        - $SNAP/share/icons/qualia-lightblue
        - $SNAP/share/icons/qualia-blue
        - $SNAP/share/icons/qualia-magenta
        - $SNAP/share/icons/qualia-olive
        - $SNAP/share/icons/qualia-prussiangreen
        - $SNAP/share/icons/qualia-purple
        - $SNAP/share/icons/qualia-pink
        - $SNAP/share/icons/qualia-red
        - $SNAP/share/icons/qualia-sage
        - $SNAP/share/icons/qualia-viridian
        - $SNAP/share/icons/qualia-dark
        - $SNAP/share/icons/qualia-bark-dark
        - $SNAP/share/icons/qualia-blue-dark
        - $SNAP/share/icons/qualia-lightblue-dark
        - $SNAP/share/icons/qualia-magenta-dark
        - $SNAP/share/icons/qualia-olive-dark
        - $SNAP/share/icons/qualia-prussiangreen-dark
        - $SNAP/share/icons/qualia-purple-dark
        - $SNAP/share/icons/qualia-pink-dark
        - $SNAP/share/icons/qualia-red-dark
        - $SNAP/share/icons/qualia-sage-dark
        - $SNAP/share/icons/qualia-viridian-dark
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/qualia

parts:
  # dg-adw-gtk3
  dg-adw-gtk3:
    after: [utils]
    source: https://github.com/dgsasha/dg-adw-gtk3.git
    source-depth: 1
    source-commit: 22adc7a519d756ea8703bb84076c86a5cefbe935
    plugin: meson
    meson-parameters:
      - --prefix=/
    build-packages:
      - sassc
      - rsync
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
    stage:
      - share/themes

  # dg-yaru
  dg-yaru:
    after: [utils]
    source: https://github.com/dgsasha/dg-yaru.git
    source-depth: 1
    source-commit: dd14e653489f09fd2ddda9bcc24f8d3a82f2cd70
    plugin: meson
    meson-parameters:
      - --prefix=/
      - -Dgnome-shell=false
      - -Dpanel-icons=false
      
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/sounds
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons
      - share/sounds

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
