name: qualia-gtk-theme
version: '1.0'
architectures:
  - build-on: amd64
    run-on: all
summary: qualia GTK theme
description: |
  A Yaru and Libadwaita inspired theme designed to provide a consistent experience on GTK desktops.
build-base: core20
base: bare
compression: lzo

grade: stable
confinement: strict

slots:
  gtk-3-themes:
    interface: content
    source:
      read:
        - $SNAP/share/themes/qualia-macos
        - $SNAP/share/themes/qualia-bark-macos
        - $SNAP/share/themes/qualia-lightblue-macos
        - $SNAP/share/themes/qualia-blue-macos
        - $SNAP/share/themes/qualia-magenta-macos
        - $SNAP/share/themes/qualia-olive-macos
        - $SNAP/share/themes/qualia-prussiangreen-macos
        - $SNAP/share/themes/qualia-purple-macos
        - $SNAP/share/themes/qualia-pink-macos
        - $SNAP/share/themes/qualia-red-macos
        - $SNAP/share/themes/qualia-sage-macos
        - $SNAP/share/themes/qualia-viridian-macos
        - $SNAP/share/themes/qualia-dark-macos
        - $SNAP/share/themes/qualia-bark-dark-macos
        - $SNAP/share/themes/qualia-lightblue-dark-macos
        - $SNAP/share/themes/qualia-blue-dark-macos
        - $SNAP/share/themes/qualia-magenta-dark-macos
        - $SNAP/share/themes/qualia-olive-dark-macos
        - $SNAP/share/themes/qualia-prussiangreen-dark-macos
        - $SNAP/share/themes/qualia-purple-dark-macos
        - $SNAP/share/themes/qualia-pink-dark-macos
        - $SNAP/share/themes/qualia-red-dark-macos
        - $SNAP/share/themes/qualia-sage-dark-macos
        - $SNAP/share/themes/qualia-viridian-dark-macos
        - $SNAP/share/themes/qualia-symbolic
        - $SNAP/share/themes/qualia-bark-symbolic
        - $SNAP/share/themes/qualia-lightblue-symbolic
        - $SNAP/share/themes/qualia-blue-symbolic
        - $SNAP/share/themes/qualia-magenta-symbolic
        - $SNAP/share/themes/qualia-olive-symbolic
        - $SNAP/share/themes/qualia-prussiangreen-symbolic
        - $SNAP/share/themes/qualia-purple-symbolic
        - $SNAP/share/themes/qualia-pink-symbolic
        - $SNAP/share/themes/qualia-red-symbolic
        - $SNAP/share/themes/qualia-sage-symbolic
        - $SNAP/share/themes/qualia-viridian-symbolic
        - $SNAP/share/themes/qualia-dark-symbolic
        - $SNAP/share/themes/qualia-bark-dark-symbolic
        - $SNAP/share/themes/qualia-lightblue-dark-symbolic
        - $SNAP/share/themes/qualia-blue-dark-symbolic
        - $SNAP/share/themes/qualia-magenta-dark-symbolic
        - $SNAP/share/themes/qualia-olive-dark-symbolic
        - $SNAP/share/themes/qualia-prussiangreen-dark-symbolic
        - $SNAP/share/themes/qualia-purple-dark-symbolic
        - $SNAP/share/themes/qualia-pink-dark-symbolic
        - $SNAP/share/themes/qualia-red-dark-symbolic
        - $SNAP/share/themes/qualia-sage-dark-symbolic
        - $SNAP/share/themes/qualia-viridian-dark-symbolic
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/share/icons/qualia
        - $SNAP/share/icons/qualia-bark
        - $SNAP/share/icons/qualia-lightblue
        - $SNAP/share/icons/qualia-blue
        - $SNAP/share/icons/qualia-magenta
        - $SNAP/share/icons/qualia-olive
        - $SNAP/share/icons/qualia-prussiangreen
        - $SNAP/share/icons/qualia-purple
        - $SNAP/share/icons/qualia-pink
        - $SNAP/share/icons/qualia-red
        - $SNAP/share/icons/qualia-sage
        - $SNAP/share/icons/qualia-viridian
        - $SNAP/share/icons/qualia-dark
        - $SNAP/share/icons/qualia-bark-dark
        - $SNAP/share/icons/qualia-blue-dark
        - $SNAP/share/icons/qualia-lightblue-dark
        - $SNAP/share/icons/qualia-magenta-dark
        - $SNAP/share/icons/qualia-olive-dark
        - $SNAP/share/icons/qualia-prussiangreen-dark
        - $SNAP/share/icons/qualia-purple-dark
        - $SNAP/share/icons/qualia-pink-dark
        - $SNAP/share/icons/qualia-red-dark
        - $SNAP/share/icons/qualia-sage-dark
        - $SNAP/share/icons/qualia-viridian-dark
  sound-themes:
    interface: content
    source:
      read:
        - $SNAP/share/sounds/qualia

parts:
  # dg-adw-gtk3
  dg-adw-gtk3:
    after: [utils]
    source: https://github.com/dgsasha/dg-adw-gtk3.git
    source-depth: 1
    source-commit: c88a3e03ed4e9ede5c68bc8431e7226bde6b1a6c
    plugin: meson
    meson-parameters:
      - --prefix=/
    build-packages:
      - sassc
      - rsync
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/themes
    stage:
      - share/themes

  # dg-yaru
  dg-yaru:
    after: [utils]
    source: https://github.com/dgsasha/dg-yaru.git
    source-depth: 1
    source-commit: 5c781db16ab944c5dd7d561ecf251ed65f94ea77
    plugin: meson
    meson-parameters:
      - --prefix=/
      - -Dgnome-shell=false
      - -Dpanel-icons=false
      
    override-build: |
      snapcraftctl build
      snapcraftctl set-version "$(git describe --tags 2>/dev/null || echo 1.0)"
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/icons
      mkdir -p $SNAPCRAFT_PART_INSTALL/share/sounds
      $SNAPCRAFT_STAGE/update-icon-cache.sh $SNAPCRAFT_PART_INSTALL/share/icons
    stage:
      - share/icons
      - share/sounds

  utils:
    plugin: dump
    source: utils
    prime:
      - -*
    build-packages:
      - try: [gtk-update-icon-cache]
      - else: [libgtk-3-bin]
